version: '3.8'
services:
  project-nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    environment:
      # - NGINX_HOST=test.appskimo.com
      - NGINX_PORT=80

  project-mysql-server:
    image: "mariadb:latest"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: project_local
      # MYSQL_USER: dominic
      # MYSQL_PASSWORD:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    volumes:
      - project-db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    # networks:
    #   - project-backend

  project-redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "16379:6379"
    volumes:
      - project-redis-data:/var/lib/redis
    # networks:
    #   project-backend:

volumes:
  project-db-data:
  project-redis-data:

# networks:
  # project-frontend:
  # project-backend: